import pic1 from "../../../images/profile/small/pic1.jpg";

const FreeMemberEvent = {
   data: [
      [
         pic1,
         "Gavin Joyce",
         "2nd",
         "Male",
         "4 year",
         "1234567890",
         "info@example.com",
         "2011/04/25",
         "",
      ],
      [
         pic1,
         "Gavin Joyce",
         "2nd",
         "Male",
         "4 year",
         "1234567890",
         "info@example.com",
         "2011/04/25",
         "",
      ],
      [
         pic1,
         "Gavin Joyce",
         "2nd",
         "Male",
         "4 year",
         "1234567890",
         "info@example.com",
         "2011/04/25",
         "",
      ],
      [
         pic1,
         "Gavin Joyce",
         "2nd",
         "Male",
         "4 year",
         "1234567890",
         "info@example.com",
         "2011/04/25",
         "",
      ],
      [
         pic1,
         "Gavin Joyce",
         "2nd",
         "Male",
         "4 year",
         "1234567890",
         "info@example.com",
         "2011/04/25",
         "",
      ],
      [
         pic1,
         "Gavin Joyce",
         "2nd",
         "Male",
         "4 year",
         "1234567890",
         "info@example.com",
         "2011/04/25",
         "",
      ],
      [
         pic1,
         "Gavin Joyce",
         "2nd",
         "Male",
         "4 year",
         "1234567890",
         "info@example.com",
         "2011/04/25",
         "",
      ],
      [
         pic1,
         "Gavin Joyce",
         "2nd",
         "Male",
         "4 year",
         "1234567890",
         "info@example.com",
         "2011/04/25",
         "",
      ],
      [
         pic1,
         "Gavin Joyce",
         "2nd",
         "Male",
         "4 year",
         "1234567890",
         "info@example.com",
         "2011/04/25",
         "",
      ],
      [
         pic1,
         "Gavin Joyce",
         "2nd",
         "Male",
         "4 year",
         "1234567890",
         "info@example.com",
         "2011/04/25",
         "",
      ],
      [
         pic1,
         "Gavin Joyce",
         "2nd",
         "Male",
         "4 year",
         "1234567890",
         "info@example.com",
         "2011/04/25",
         "",
      ],
      [
         pic1,
         "Gavin Joyce",
         "2nd",
         "Male",
         "4 year",
         "1234567890",
         "info@example.com",
         "2011/04/25",
         "",
      ],
      
      [
         pic1,
         "Gavin Joyce",
         "2nd",
         "Male",
         "4 year",
         "1234567890",
         "info@example.com",
         "2011/04/25",
         "",
      ],
   ],
   columns: [
      "Profile Pic",
      "Name",
      "Year",
      "Gender",
      "Membership Duration",
      "Mobile",
      "Email",
      "Joining Date",
   ],
};

const data = {
   FreeMemberEvent,
};

export default data;
